test:
		@echo skipped && exit 0
test-cov:
		@echo skipped && exit 0
test-cov-html:
		@echo skipped && exit 0
test-bamboo:
		@echo skipped && exit 0
test-cov-bamboo:
		@echo skipped && exit 0
test-code-style:
		@echo skipped && exit 0
test-code-style-bamboo:
		@echo skipped && exit 0
jshint:
		@echo skipped && exit 0
jshint-bamboo:
		@echo skipped && exit 0

.PHONY: test test-cov test-cov-html test-bamboo test-cov-bamboo jshint jshint-bamboo test-code-style test-code-style-bamboo
